# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: b.gcr.io/cloudsql-docker/gce-proxy
  tag: latest
gcp:
  project: projectname
  region: europe-west2
  instance: cloudsql-instance
bind:
  addr: 0.0.0.0
  port: 3306
service:
  name: cloudsql-proxy
  type: ClusterIP
  internalPort: 3306
  externalPort: 3306
credentials: 
  path: /secrets/cloudsql
  file: credentials.json
  secret: cloudsql-credentials
  secret_enabled: true
  b64enc: 
ssl:
  path: /etc/ssl/certs
  hostpath: /etc/ssl/certs
