{{- if .Values.credentials.secret_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-credentials
data:
  {{ .Values.credentials.file }}: |-
  {{- if .Values.credentials.b64enc }}
    {{ .Values.credentials.b64enc }}
  {{- else }}
    {{- $file := .Values.credentials.file }}
    {{ .Files.Get $file | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
